baseurl: ""
url: "http://www.thiagonevesfotografia.com.br"

title: Thiago Neves | Fotografia
email: thiagohneves@gmail.com
description: ""

source:      .
destination: ./_site
plugins:     ./_plugins

css_folder: "assets/stylesheets"
js_folder:  "assets/javascripts"
img_folder: "assets/images"

exclude:
  - node_modules/
  - Gruntfile.js
  - package.json
  - README.md
  - deploy.yml

markdown: kramdown
permalink: pretty
