baseurl: "localhost:4000/"
url: "http://www.thiagonevesfotografia.com.br"

title: Thiago Neves | Fotografia
email: thiagohneves@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

google-analytics-tracking-id:

source:      .
destination: ./_site
plugins:     ./_plugins

css_folder: "assets/stylesheets"
js_folder:  "assets/javascripts"
img_folder: "assets/images"

exclude:
  - node_modules/
  - Gruntfile.js
  - package.json
  - README.md

markdown: kramdown
permalink: pretty
